# Invoice
Starter\BillingBundle\Entity\Invoice:
    properties:
        description:
            - NotBlank: ~
        price:
            - NotBlank: ~
        status:
            - NotBlank: ~
        billing:
            - NotBlank: ~